name: CATSMPMC
main: me.yusufkerem.CATSMPMC
version: 1.0
api-version: 1.21
commands:
  catsmp:
    description: Main CatSMP command
    usage: /catsmp <sub>
  zoom:
    description: Dash ability for Passive cats
  zoomcombo:
    description: Toggle sneak+jump dash
  role:
    description: Admin role command
permissions:
  catsmp.addbp:
    default: op
  catsmp.removebp:
    default: op
  catsmp.setbp:
    default: op
  catsmp.checkbp.others:
    default: op
  catsmp.admin:
    default: op


