name: CATSMPMC
version: 1.0.0
main: me.yusufkerem.CATSMPMC
api-version: 1.19
author: YusufKerem
description: Cat SMP Minecraft Plugin with roles and abilities

commands:
  catsmp:
    description: Main CATSMP command
    usage: /catsmp <subcommand>
    aliases: [cat, csmp]
  zoom:
    description: Trigger dash ability
    usage: /zoom
  zoomcombo:
    description: Toggle sneak+jump combo for zoom
    usage: /zoomcombo
  role:
    description: Manage player roles
    usage: /role set <player> <passive|aggressive>
    permission: catsmp.admin

permissions:
  catsmp.admin:
    description: Administrative permissions for CATSMP
    default: op
  catsmp.addbp:
    description: Permission to add blood points
    default: op
  catsmp.removebp:
    description: Permission to remove blood points
    default: op
  catsmp.setbp:
    description: Permission to set blood points
    default: op
  catsmp.checkbp.others:
    description: Permission to check other players' blood points
    default: op


